name: Deploy to Server

on:
  push:
    branches: [ main ]  # 當推送到主分支時觸發
  workflow_dispatch:    # 允許手動觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 創建或進入部署目錄
            mkdir -p ~/app
            cd ~/app
            
            # 如果目錄已存在，清理舊版本
            if [ -d ".git" ]; then
              git pull
            else
              # 克隆倉庫
              git clone ${{ secrets.REPO_URL }} .
            fi
            
            # 安裝依賴
            export PATH="$PATH:~/.local/share/pnpm"
            pnpm install
            
            # 使用PM2啟動或重啟應用
            if pm2 list | grep -q "app-name"; then
              pm2 restart app-name
            else
              pm2 start "pnpm run dev" --name "app-name"
            fi
